### ISSUE TITLE
pong is only using the name of the first TestNG suite found in the testng-results.xml file

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#11]
Look at these two polarion test runs uploaded from the same jenkins job https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/create-polarion-testrun/76/  ...

RHSM GUI Acceptance TestSuite RHEL-6 8-20160224 n 0 Server x86_64 Run 1 (RHSM RHEL6-8)
RHSM GUI Acceptance TestSuite RHEL-6 8-20160224 n 0 Server x86_64 Run 2 (RHSM RHEL6-8)

https://polarion.engineering.redhat.com/polarion/#/project/RHEL6/testrun?id=RHSM%20GUI%20Acceptance%20TestSuite%20RHEL%2D6%208%2D20160224%20n%200%20Server%20x86%5F64%20Run%201

https://polarion.engineering.redhat.com/polarion/#/project/RHEL6/testrun?id=RHSM%20GUI%20Acceptance%20TestSuite%20RHEL%2D6%208%2D20160224%20n%200%20Server%20x86%5F64%20Run%202

Respectively, they should have been...
RHSM GUI Acceptance TestSuite RHEL-6 8-20160224 n 0 Server x86_64 Run 1 (RHSM RHEL6-8)
RHSM CLI Acceptance TestSuite RHEL-6 8-20160224 n 0 Server x86_64 Run 1 (RHSM RHEL6-8)

**Comment by rarebreed** [comment]
Fixed in 9d8f5bb5e5a77c33bcfee6a59e026e1e4be3c549
