### ISSUE TITLE
add a new option for --testrun-groupId

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#28]
I've noticed that some teams are starting to populate the "Build ID" property on their polarion testruns.
I would like to do the same.  I only need Pong to provide a new command line option for...

  --testrun-groupId

Then the value that I provide you will by uploaded to the polarion testrun-property:groupId

I think this is a simple string property and should operate the same way as pong --testrun-notes uploads to polarion testrun-property:notes.

**Comment by rarebreed** [comment]
There is now a new field called --testrun-group-id that defaults to an empty string.  Whatever is put here will go into the Build Id: field in the TestRun in Polarion.

https://github.com/RedHatQE/pong/commit/101d4f073349a1d3312b74c0d6b93081f3bb8b0a
