### ISSUE TITLE
BASE_QUERIES

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#5]
In the --help info, it indicates an example should include the query type such as 'title:' within the query.  I agree with this... 

  -b [BASE_QUERIES [BASE_QUERIES ...]], --base-queries [BASE_QUERIES [BASE_QUERIES ...]]
                        A sequence of strings that will be used for TestCase
                        title searches eg 'title:<base_query>')

However when I specify --base-queries=title:rhsm._.tests_ an exception is thrown...

 com.polarion.subterra.index.QueryIndexException: Failed to parse query: (title:title:rhsm._.tests_ AND type:testcase AND project.id:RHEL6) AND NOT IS_LOCAL:true'

notice that the code is automatically inserting another 'title:'  I think you should not automatically insert another 'title'.

**Comment by rarebreed** [comment]
fixed in commit 5e14081a99c5eff5a99a60c120ecc0da2fa75042
