### ISSUE TITLE
testrun index improvement

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#6]
Rather than appending a counting " #" to the title of a testrun, I think you should append " Run #".
I think this makes the title of the test run more pleasant to read especially when the testrun-suffix ends in a RHEL COMPOSE_ID.  This will prevent the run number from getting interpreted by the user as part of the compose number.
Moreover, the regex that you use to find existing testruns by the same name would be more robust if you are searching for matches to ^(.+)\s+Run (\d+)$

**Comment by rarebreed** [comment]
Fixed in commit 4118da292566d1c02f246f6cc98977cb2cb098ff
