### ISSUE TITLE
the very first testrun is missing a " Run " prefix before the testrun indexor

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#8]
See https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/QE-RHEL6.8/job/create-polarion-testrun/45/console

1455774850.7-pong.logger-INFO:  Created test run for RHSM CLI Tier1 TestSuite Server x86_64 1

Expected: RHSM CLI Tier1 TestSuite Server x86_64 Run 1

**Comment by rarebreed** [comment]
Fixed in commit 013939d4945a48d2576b4b703604bbfcbc478040
