### ISSUE TITLE
pylarion.exceptions.PylarionLibException: string must be UTF-8

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#9]
See  https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/QE-RHEL6.8/job/create-polarion-testrun/64/console

I have the following test description which contains a character that pylarion is choking on...
    @Test(  description="verify that translation msgstr does NOT contain paragraph character ¶ unless also in msgid",

What do you suggest?  Should I just change the description?  Or do you have a workaround within pong?

**Comment by omaciel** [comment]
@jsefler tried this yet?

``` python
@Test( description=u"verify that translation msgstr ...",
```

**Comment by omaciel** [comment]
Looks like this can now be closed?

**Comment by omaciel** [comment]
See this pull request: https://github.com/RedHatQE/pong/pull/10

**Comment by rarebreed** [comment]
Fixed in 774330845ffccfb5e80ad66cb55318401e100625
